[tool.isort]
profile = 'black'
src_paths = './'
skip = 'migrations,venv'
skip_glob = 'tests/*'
# default_section = 'THIRDPARTY'
sections=FUTURE,STDLIB,FIRSTPARTY,THIRDPARTY,LOCALFOLDER
known_first_party = ['recipes', 'users']
known_local_folder = ['recipes', 'users']
multi_line_output = 3
line_length = 79